flowchart TD
  subgraph OpenRoom
    subgraph OpenDoor
        subgraph "PrepareSill[r,c,seed] 1..3"
            psx[[singlecellchange]]
            setdoortype["setdoortype(rand)"]
            psx--> setdoortype
        end
        B[Execute Subcommands]
        C[Cleanup]
    end

    subgraph Subcommands
        B1[Subcommand A]
        B2[Subcommand B]
        B3[Subcommand C]
    end

  end
  A --> B --> C
  B --> B1 --> B2 --> B3
